# Generated by Django 2.2 on 2019-04-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openaqi_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='secret_seed',
        ),
    ]
