# Generated by Django 2.2 on 2019-04-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaqi_web', '0002_remove_sensor_secret_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
