# Generated by Django 2.2 on 2019-04-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openaqi_web', '0004_auto_20190406_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_10', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='PM10')),
                ('pm_25', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='PM2.5')),
                ('pm_1', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='PM1')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openaqi_web.Sensor')),
            ],
        ),
    ]
