# Generated by Django 2.2 on 2019-04-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaqi_web', '0006_auto_20190406_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
