# Generated by Django 2.2 on 2019-04-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaqi_web', '0008_auto_20190406_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
